language: node_js
node_js:
  - "5.8"
  - "4.4"
  #- "0.12" We will not be supporting 0.12 as Node retired it
  #- "0.10" We will not be supporting 0.10 as Node retired it

sudo: required

script:
  - npm run build

notifications:
  slack:
    rooms:
      - thunderflurry:1FIUTNPm9dDb9nPDh4fzVgPT#dev-travis
  email:
    - victoria.french@cinecove.com

git:
  depth:
    10

#cache:
#  directories:
#    - node_modules
