language: node_js
node_js:
  - "5.7"
  - "4.3"
  - "0.12"
  - "0.10"

sudo: required

script:
  - npm build

notifications:
  slack: 
    rooms:
      - thunderflurry:1FIUTNPm9dDb9nPDh4fzVgPT#dev-travis
  email:
    - victoria.french@cinecove.com

git:
  depth:
    10

cache:
  directories:
    - node_modules
